version: '3'

services:
  postgres:
    container_name: "posgres"
    image: postgres
    ports:
      - 5432:5433
    environment:
      - POSTGRES_PASSWORD:"root"
      - POSTGRES_USER:"root"
      
  